# Generated by Django 3.2 on 2021-04-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name: ', max_length=50)),
                ('money', models.FloatField(help_text='Enter money: ')),
            ],
        ),
    ]
