# Generated by Django 3.2 on 2021-04-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clubs',
            new_name='club',
        ),
    ]
